### ISSUE TITLE
Deleting category returns not found

### ISSUE THREAD

**Issue by spoyntersmith** [alvarezskinner/pantry-app-backend#6]
@alvarezskinner 
Is it possible to return "Category deleted" or something similar?
I think that somehow the show() by {id} function runs

Steps to reproduce:
Create new Category - POST { "name": "Category 1" } > http://127.0.0.1:8000/api/categories/
Delete Category - DELETE > http://127.0.0.1:8000/api/categories/{id}

**Comment by alvarezskinner** [comment]
Sure we could do that, although we would normally check the status code, not the response body message to confirm. What is the reason you believe we need this?

**Comment by spoyntersmith** [comment]
/**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $cat = Category::find($id);
            if ($cat == null) {
                return response()->json(['message' => 'Category not found'], 404);
            }
            $cat->delete();
            return response()->json([], 204); // No Content
        } catch (Exception $e) {
            return response()->json(['message' => $e->getMessage()], 500);
        }
    }

[Line 94](https://github.com/alvarezskinner/pantry-app-backend/blob/d08d679ce006238b07f7d4d02d685d5ae824b169/app/Http/Controllers/CategoryController.php#L94) ( `return response()->json([], 204); // No Content` ) 
Never fires, when looking up a category that doesn't exist and deleting a category the result is 404.

Do we want to remove this line and assume that 404 means category deleted? Does that make sense?

**Comment by alvarezskinner** [comment]
Not sure what you mean, you mean deletions never work, or that the response is always empty?

**Comment by spoyntersmith** [comment]
Response is always 'Category not found' 404
